services:
  postgres:
    image: postgres:16
    container_name: error-reporter-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: error_reporter
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
